### PR TITLE
kmsbasertpendpoint: Request RTCP mux sinkpad on rtpbin if it does not…

### PR DESCRIPTION
**Pull request by sdroege**
… exist yet

### CODE REVIEW

**Comment by jcaden** [comment]
Pushed to gerrit. Review is in progress. Thanks.

**Comment by jcaden** [comment]
Just curiosity, have experienced a segmentation fault caused by this? Or is something you just found reading the code?

**Comment by sdroege** [comment]
It happened, yes. You might also have to replace the other get_request_pad() and get_static_pad() calls with a similar construct... get_request_pad() behaviour is undefined (and you get a warning) if a pad with that name exists already.

**Comment by jcaden** [comment]
Thanks we will examine it in detail.

**Comment by jcaden** [comment]
Accepted now

**Pull request closed without merging**
